from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='VehicleCategory', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=100)),
            ('slug', models.CharField(choices=[('two_wheeler','Two Wheeler'),('three_wheeler','Three Wheeler'),('four_wheeler','Four Wheeler')], max_length=50, unique=True)),
            ('description', models.TextField(blank=True)),
            ('icon', models.CharField(default='🚗', max_length=10)),
            ('cover_color', models.CharField(default='#E85C0D', max_length=20)),
        ], options={'verbose_name_plural': 'Vehicle Categories'}),
        migrations.CreateModel(name='UserProfile', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('role', models.CharField(choices=[('buyer','Buyer'),('seller','Seller')], default='buyer', max_length=10)),
            ('phone', models.CharField(blank=True, max_length=20)),
            ('location', models.CharField(blank=True, max_length=200)),
            ('bio', models.TextField(blank=True)),
            ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ('is_verified', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='Seller', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=150)),
            ('phone', models.CharField(max_length=20)),
            ('email', models.EmailField()),
            ('location', models.CharField(max_length=200)),
            ('avatar', models.ImageField(blank=True, null=True, upload_to='sellers/')),
            ('bio', models.TextField(blank=True)),
            ('is_verified', models.BooleanField(default=False)),
            ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
            ('total_sales', models.PositiveIntegerField(default=0)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.CreateModel(name='Vehicle', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('title', models.CharField(max_length=200)),
            ('brand', models.CharField(max_length=100)),
            ('model_name', models.CharField(max_length=100)),
            ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ('fuel_type', models.CharField(choices=[('petrol','Petrol'),('diesel','Diesel'),('electric','Electric'),('hybrid','Hybrid'),('cng','CNG')], max_length=20)),
            ('year', models.IntegerField()),
            ('mileage', models.CharField(max_length=50)),
            ('km_driven', models.PositiveIntegerField(default=0)),
            ('condition', models.CharField(choices=[('new','Brand New'),('excellent','Excellent'),('good','Good'),('fair','Fair')], default='good', max_length=20)),
            ('color', models.CharField(blank=True, max_length=50)),
            ('engine_cc', models.CharField(blank=True, max_length=30)),
            ('description', models.TextField(blank=True)),
            ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ('image2', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ('image3', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
            ('status', models.CharField(choices=[('active','Active'),('sold','Sold'),('inactive','Inactive')], default='active', max_length=20)),
            ('is_featured', models.BooleanField(default=False)),
            ('is_negotiable', models.BooleanField(default=True)),
            ('views_count', models.PositiveIntegerField(default=0)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.vehiclecategory')),
            ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.seller')),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='SavedListing', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='marketplace.vehicle')),
        ], options={'unique_together': {('user', 'vehicle')}}),
        migrations.CreateModel(name='Review', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('rating', models.PositiveSmallIntegerField(default=5)),
            ('comment', models.TextField()),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.seller')),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ], options={'unique_together': {('seller', 'user')}}),
        migrations.CreateModel(name='Enquiry', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(max_length=100)),
            ('email', models.EmailField()),
            ('phone', models.CharField(max_length=20)),
            ('message', models.TextField()),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='marketplace.vehicle')),
        ]),
        migrations.CreateModel(name='Conversation', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.vehicle')),
            ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
            ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to='marketplace.seller')),
        ], options={'ordering': ['-updated_at'], 'unique_together': {('vehicle', 'buyer', 'seller')}}),
        migrations.CreateModel(name='Message', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('body', models.TextField()),
            ('is_read', models.BooleanField(default=False)),
            ('sent_at', models.DateTimeField(auto_now_add=True)),
            ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.conversation')),
            ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
        ], options={'ordering': ['sent_at']}),
        migrations.CreateModel(name='VehicleBookingRequest', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('status', models.CharField(choices=[('pending','Pending'),('accepted','Accepted'),('rejected','Rejected'),('completed','Completed')], default='pending', max_length=20)),
            ('message', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='marketplace.vehicle')),
            ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
            ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='marketplace.seller')),
        ]),
    ]
